spring:
  application:
    name: EUREKA_SERVER
  profiles:
    active: dev

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    web: error
