spring:
  profiles:
    active: dev
  application:
    name: APP_GATEWAY
  cloud:
    gateway:
      routes:
        - id: usersModule
          uri: lb://USERS
          predicates:
            - Path=/users/**
        - id: reviewMoule
          uri: lb://REVIEWS
          predicates:
            - Path=/reviews/**
        - id: vendorModule
          uri: lb://VENDORS
          predicates:
            - Path=/vendors/**
logging:
  level:
    web: error
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
