spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
logging:
  level:
    web: debug
server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka